name: Build
run-name: Build
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  - push
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Generate project
        run: .\msvc.bat
      - name: Build
        run: |
          cd msvc
          msbuild buxn-ls.sln /property:Configuration=RelWithDebInfo /property:Platform=x64
      - name: Test
        run: |
          .\bin\RelWithDebInfo\buxn-jit-tests.exe
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
      - name: Setup mold
        uses: rui314/setup-mold@v1
        with:
          mold-version: 2.37.1
      - name: Build
        run: BUILD_TYPE=RelWithDebInfo ./build
      - name: Test
        env:
          BUILD_TYPE: RelWithDebInfo
        run: |
          ./test
  build-freebsd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build in FreeBSD
        id: test
        uses: vmactions/freebsd-vm@v1.2.3
        with:
          usesh: true
          prepare: |
            pkg install -y cmake mold ninja llvm20
          run: |
            export PATH=/usr/local/llvm20/bin:$PATH
            export BUILD_TYPE=RelWithDebInfo
            ./build
            sh ./test
